<?php

/**
 * @file
 * Contains ckeditor_simplebutton.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_simplebutton_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ckeditor_simplebutton module.
    case 'help.page.ckeditor_simplebutton':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides Button plugin to CKEditor') . '</p>';
      return $output;

    default:
  }
}
